### ISSUE TITLE
Bug: vlab service dev error

### ISSUE THREAD

**Issue by denis-ev** [VivumLab/VivumLab#256]
**Describe the bug**
```
root@4b6ab1cc0f80:/data# vlab service list
/usr/local/bundle/gems/tty-table-0.12.0/lib/tty/table/validatable.rb:25:in `block in assert_row_sizes': row size differs (10 should be 5) (TTY::Table::DimensionMismatchError)
        from /usr/local/bundle/gems/tty-table-0.12.0/lib/tty/table/validatable.rb:23:in `each'
        from /usr/local/bundle/gems/tty-table-0.12.0/lib/tty/table/validatable.rb:23:in `assert_row_sizes'
        from /usr/local/bundle/gems/tty-table-0.12.0/lib/tty/table.rb:121:in `initialize'
        from /usr/local/bundle/gems/tty-table-0.12.0/lib/tty/table.rb:96:in `new'
        from /usr/local/bundle/gems/tty-table-0.12.0/lib/tty/table.rb:96:in `new'
        from /data/tasks/service.rb:15:in `list'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from /usr/local/bin/vlab:121:in `<main>'
```

**To Reproduce**
Pull current dev (1.0.0) and run `vlab service list`

**Expected behavior**
List services

**Desktop (please complete the following information):**
 - Vivumlab Version: dev

**Additional context**

**Comment by codefriar** [comment]
@denis-ev just tried to reproduce, cannot reproduce. 

```
root@96a08a916ec7:/data# vlab service list
┌─────────────┬───────────────┬────────────┬───────────────────┬──────────────────────┐
│adguardhome  │airsonic       │apache2     │apple_health_influx│authelia              │
│barcodebuddy │beets          │bitwarden   │bookstack          │calibre               │
│chowdown     │cockpit        │codeserver  │codimd             │darksky_influx        │
│digikam      │docs           │drone       │duckdns            │duplicati             │
│elkstack     │emby           │erpnext     │ethercalc          │factorio              │
│firefly_iii  │folding_at_home│freshrss    │funkwhale          │ghost                 │
│gitea        │gitlab         │gotify      │grafana            │grocy                 │
│guacamole    │hastebin       │healthchecks│heimdall           │homeassistant         │
│homebridge   │homedash       │hubzilla    │huginn             │invoiceninja          │
│jackett      │jellyfin       │jenkins     │keycloak           │kutt                  │
│lazylibrarian│librephotos    │lidarr      │mailu              │massivedecks          │
│matomo       │matterbridge   │mayan       │minecraft          │minecraftbedrockserver│
│miniflux     │minio          │monicahq    │mstream            │mylar3                │
│n8n          │netdata        │nextcloud   │nodered            │nzbget                │
│octoprint    │ombi           │openldap    │openvpn            │organizr              │
│paperless    │peertube       │photoprism  │pihole             │piwigo                │
│pixelfed     │pleroma        │plex        │poli               │portainer             │
│privatebin   │qbittorrent    │radarr      │readarr            │restic                │
│rsshub       │sabnzbd        │samba       │searx              │shinobi               │
│sickchill    │simply_shorten │snibox      │sonarr             │speedtest             │
│statping     │sui            │syncthing   │taisun             │tautulli              │
│teedy        │thelounge      │tick        │tiddlywiki         │tor                   │
│transmission │trilium        │turtl       │ubooquity          │unificontroller       │
│wallabag     │watchtower     │webdavserver│webtrees           │webvirtmgr            │
│wekan        │wificard       │zammad      │zulip              │                      │
└─────────────┴───────────────┴────────────┴───────────────────┴──────────────────────┘
```

**Comment by denis-ev** [comment]
That's so weird, I did a fresh pull and still got that error.
I even check if my repo is clean and no unstaged or staged changes.

**Comment by codefriar** [comment]
@denis-ev - I'm trying to think of things that could be different between our setups. but with it being in the docker container... I'm not sure what could cause it. @voryzen and I both checked that command before we merged to dev
